const synonyms = {
    s: 'seconds',
    sec: 'seconds',
    secs: 'seconds',
    second: 'seconds',
    seconds: 'seconds',
    m: 'minutes',
    min: 'minutes',
    mins: 'minutes',
    minute: 'minutes',
    minutes: 'minutes',
    h: 'hours',
    hrs: 'hours',
    hour: 'hours',
    hours: 'hours',
    d: 'days',
    day: 'days',
    days: 'days',
    mon: 'months',
    mnt: 'months',
    mnth: 'months',
    mnths: 'months',
    mnts: 'months',
    month: 'months',
    months: 'months',
    y: 'years',
    yr: 'years',
    yrs: 'years',
    year: 'years',
    years: 'years',
    ago: 'before now',
    quarter: '15 minutes',
    half: '30 minutes',
    from: 'after',
    jan: 'january',
    feb: 'february',
    mar: 'march',
    apr: 'april',
    jun: 'june',
    jul: 'july',
    aug: 'august',
    sep: 'september',
    oct: 'october',
    nov: 'november',
    dec: 'december'
};

function get(text) {
    return synonyms[text];
}

module.exports.get = get;
