const synonyms = {
    s: 'seconds',
    sec: 'seconds',
    seg: 'seconds',
    secs: 'seconds',
    segs: 'seconds',
    second: 'seconds',
    segundo: 'seconds',
    seconds: 'seconds',
    segundos: 'seconds',
    m: 'minutes',
    min: 'minutes',
    mins: 'minutes',
    minuto: 'minutes',
    minutos: 'minutes',
    minute: 'minutes',
    minutes: 'minutes',
    h: 'hours',
    hrs: 'hours',
    hour: 'hours',
    hora: 'hours',
    horas: 'hours',
    hours: 'hours',
    d: 'days',
    day: 'days',
    days: 'days',
    dia: 'days',
    dias: 'days',
    mon: 'months',
    mes: 'months',
    mnt: 'months',
    mnth: 'months',
    mnths: 'months',
    mnts: 'months',
    month: 'months',
    months: 'months',
    y: 'years',
    yr: 'years',
    yrs: 'years',
    year: 'years',
    years: 'years',
    anio: 'years',
    'año': 'years',
    'años': 'years',
    ago: 'before now',
    quarter: '15 minutes',
    cuarto: '15 minutes',
    half: '30 minutes',
    from: 'after',

    jan: 'january',
    feb: 'february',
    mar: 'march',
    apr: 'april',
    jun: 'june',
    jul: 'july',
    aug: 'august',
    sep: 'september',
    oct: 'october',
    nov: 'november',
    dec: 'december',

    ene: 'january',
    feb: 'february',
    mar: 'march',
    abr: 'april',
    may: 'may',
    jun: 'june',
    jul: 'july',
    ago: 'august',
    sep: 'september',
    oct: 'october',
    nov: 'november',
    dic: 'december',

    'antes': 'before',
    'despues': 'after',
    'dentro': 'after',
    'desde': 'after',
    'en': 'after',
    // Clean words
    'de': ' ',
    'el': ' ',
    'las': ' ',

};

function get(text) {
    return synonyms[text];
}

module.exports.get = get;
